mysite/company/urls.py
from django.conf.urls import url
from company import views

app_name = "company"

urlpatterns = [

    url(r'^$', views.CompanyProfileListView.as_view(), name = "company_dashboard"),
    url(r'^jobs_dashboard/$', views.CompanyJobsDashboard, name='company_jobs_dashboard'),
    url(r'^companyprofile/$', views.CompanyProfileView.as_view(), name = "company_profile_form"),
    url(r'^company_update/(?P<pk>\d+)/$', views.CompanyProfileUpdateView.as_view(), name = 'company_update'),
    url(r'^(?P<pk>\d+)/$', views.CompanyProfileDetailView.as_view(), name = 'company_detail'),
    url(r'^job_dash/$',  views.CompanyJobsDashboard, name = 'company_dash'),

    url(r'^job_create/$', views.JobCreateView.as_view(), name = 'job_create'),
    url(r'^job_update/(?P<pk>\d+)/$', views.JobUpdateView.as_view(), name = 'job_update'),
    url(r'^job_detail/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name = 'job_detail'),
    url(r'^job_delete/(?P<pk>\d+)/$', views.JobDeleteView.as_view(), name = 'job_delete'),
    url(r'^user_object_detail/(?P<candidate_id>\d+)/$', views.ShowCandidateDetail, name = 'user_detail'),
    url(r'^selected/(?P<job_id>\d+)/$', views.Selected, name = "selected"),
    url(r'^rejected/(?P<job_id>\d+)/$', views.Rejected, name = "rejected"),
    url(r'^applicants/$', views.AllApplicantsView, name = "all_applicants"),
    url(r'^candidates/$', views.AllCandidatesView, name = "all_candidates"),
    url(r'^candidate_detail/(?P<key_id>\d+)/$', views.CandidateDisplay, name = "candidate_detail"),
    url(r'^download_resume/(?P<user_id>\d+)/$', views.GetResume, name = "get_resume"),
    url(r'^analysis_page/$', views.AnalysisPage.as_view(), name = "analysis_page")
]

mysite/editor/urls.py
from django.conf.urls import url
from editor import views

app_name = 'editor'

urlpatterns = [
    url(r'^$', views.typingEditor , name = 'typingEditor'),
]

mysite/job_seeker/urls.py
from django.conf.urls import url
from job_seeker import views

app_name = "job_seeker"

urlpatterns = [
    # url(r'^$', views.UserDashBoard.as_view(), name = "user_dashboard"),
    url(r'^$', views.UserModelList.as_view(), name = "usermodel_list"),
    url(r'^(?P<pk>\d+)/$', views.UserProfileDetailView.as_view(), name = "detail"),
    url(r'^personal/$', views.UserProfileCreateView.as_view(), name = "user_profile_form"),
    url(r'^update/(?P<pk>\d+)/$', views.UserProfileUpdateView.as_view(), name = "update_profile_form"),

    url(r'^pro/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name = "project_detail"),
    url(r'^pro_update/(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name = "project_update"),
    url(r'^project/$', views.ProjectCreateView.as_view(), name = "create_project"),
    url(r'^delete/(?P<pk>\d+)/$', views.ProjectDeleteView.as_view(), name = "project_delete"),

    url(r'^skill/$', views.SkillCreateView.as_view(), name = "create_skill"),
    url(r'^skill_update/(?P<pk>\d+)/$', views.SkillUpdateView.as_view(), name = "skill_update"),
    url(r'^skill/(?P<pk>\d+)/$', views.SkillDetailView.as_view(), name = "skill_detail"),
    url(r'^skill_delete/(?P<pk>\d+)/$', views.SkillDeleteView.as_view(), name = "skill_delete"),

    url(r'^award/$', views.AwardCreateView.as_view(), name = "create_award"),
    url(r'^award_update/(?P<pk>\d+)/$', views.AwardUpdateView.as_view(), name = "award_update"),
    url(r'^award/(?P<pk>\d+)/$', views.AwardDetailView.as_view(), name = "award_detail"),
    url(r'^award_delete/(?P<pk>\d+)/$', views.AwardDeleteView.as_view(), name = "award_delete"),

    url(r'^certification/$', views.CertificationCreateView.as_view(), name = "create_certification"),
    url(r'^certification_update/(?P<pk>\d+)/$', views.CertificationUpdateView.as_view(), name = "certification_update"),
    url(r'^certification/(?P<pk>\d+)/$', views.CertificationDetailView.as_view(), name = "certification_detail"),
    url(r'^certification_delete/(?P<pk>\d+)/$', views.CertificationDeleteView.as_view(), name = "certification_delete"),

    url(r'^review1/$', views.Res1.as_view(), name = 'res1'),
    url(r'^review2/$', views.Res2.as_view(), name = 'res2'),
    url(r'^review3/$', views.Res3.as_view(), name = 'res3'),
    url(r'^review4/$', views.Res4.as_view(), name = 'res4'),
    url(r'^review5/$', views.Res5.as_view(), name = 'res5'),

    url(r'^dash/$', views.JobDisplay.as_view(), name = 'job_display'),
    url(r'job_detail/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name = 'job_detail'),
    url(r'apply/(?P<job_id>\d+)', views.JobApply, name = "job_apply"),
    url(r'^cancel_application/(?P<pk>\d+)/$', views.JobsDeleteView.as_view(), name = 'cancel_job'),
    url(r'^all_jobs/$', views.AllJobs.as_view(), name = "all_jobs"),
    url(r'^resume_page/$', views.ResumePage.as_view(), name = "resume_page"),
    url(r'^user_analysis_page/$', views.UserAnalysisPage.as_view(), name = "user_analysis")

]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from registration import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home'),
    url(r'^userlogin/$', views.UserLogin.as_view(), name = "user_login"),
    url(r'^companylogin/$', views.CompanyLogin.as_view(), name = "company_login"),
    url(r'^userlogout/$', views.user_logout, name = "user_logout"),
    url(r'^usersignup/$', views.UserSignUp, name = "user_signup"),
    url(r'^companysignup/$', views.CompanySignUp, name = "company_signup"),
    url(r'^job_seeker/',include('job_seeker.urls', namespace = "job_seeker") ),
    url(r'^company/', include('company.urls'), name = "company"),
    url(r'^editor/', include('editor.urls'), name = "editor")
]

mysite/templates/company_login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Company Login</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static "css/style_grid" %}">
</head>

<style type="text/css">
.field-icon {
  float: right;
  margin-left: -25px;
  margin-top: -25px;
  position: relative;
  z-index: 2;
}
.register{
	max-width: 540px;
}
</style>
<body>


<div class="container register jumbotron">
	<center> <img style="margin-top:15px;" src="https://www.winhelponline.com/blog/wp-content/uploads/2017/12/user.png" class="avatar" height = "150px" width = "150px"> </center>
	<center><h3>Company Login</h3></center>
	<form class="" action="{% url "company_login"%}" method="POST">
  {% csrf_token%}
	<div class="form-group">
		<label for="username">Username</label>
		<input type="username" name="username" id="email" class="form-control" required=True>
	</div>

	<div class="form-group">
        <label class="">Password</label>
        <input id="password-field" type="password" class="form-control" name="password">
        <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
    </div>
	<center> <p class="help is-danger">{{ message }}</p></center>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Login</button>
	</div>
	<center>
		<p>Don't have an account?</p>
		<a href="{% url "company_signup" %}" class="btn btn-info">SignUp</a>
	</center>
	</form>


</div>

</body>
</html>

<script type="text/javascript">
	$(".toggle-password").click(function() {

  $(this).toggleClass("fa-eye fa-eye-slash");
  var input = $($(this).attr("toggle"));
  if (input.attr("type") == "password") {
    input.attr("type", "text");
  } else {
    input.attr("type", "password");
  }
});
</script>

mysite/templates/company_signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>user register</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static "css/style_grid.css" %}">
</head>

<style type="text/css">
.field-icon {
  float: right;
  margin-left: -25px;
  margin-top: -25px;
  position: relative;
  z-index: 2;
}
.register{
	max-width: 540px;
}
</style>
<body>

<div class="container register jumbotron">
	<center> <img style="margin-top:15px;" src="https://www.winhelponline.com/blog/wp-content/uploads/2017/12/user.png" class="avatar" height = "150px" width = "150px"> </center>
	<center><h3>Company SignUp</h3></center>
	<!-- for displaying the message  -->
	<div class="form-group">
		{% if messages %}
		<ul class = "messages">
			{% for message in messages %}
			<div class="alert alert-success">
				<strong>Success!</strong> {{ message }}
			</div>
			{% endfor %}
		</ul>
		{% endif %}
	</div>
	<!-- end of message section -->

	<form class="" action="{% url "company_signup" %}" method="post">
	{% csrf_token %}

	<div class="form-group">
		<label for="username">Username</label>
		<!-- <input type="text" name="firstname" id="firstname" class="form-control" required=""> -->
		{{ reg_form.username }}
		{% if reg_form.username.help_text %}
			<p class="help">{{ reg_form.username.help_text }}</p>
		{% endif %}
		<p class="help is-danger">{{ reg_form.username.errors }}</p>
	</div>

	<div class="form-group">
		<label for="email">Email</label>
		<!-- <input type="text" name="lastname" id="lastname" class="form-control" required=""> -->
		{{ reg_form.email }}
		<p class="help is-danger">{{ reg_form.email.errors }}</p>
	</div>

	<div class="form-group">
		<label for="password">Password</label>
		<!-- <input type="email" name="email" id="email" class="form-control" required=""> -->
		{{ reg_form.password }}
		<div class="help is-danger">{{ reg_form.password.errors }}</div>
		<span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
	</div>

	<div class="form-group">
        <label class="">Confirm Password</label>
        <!-- <input id="password-field" type="password" class="form-control" name="password"> -->
				{{ reg_form.confirm_password }}
				<span toggle="#confirm_password-field" class="fa fa-fw fa-eye field-icon toggle-confirm_password"></span>
				<p class="help is-danger">{{ reg_form.confirm_password.errors }}</p>
    </div>

	<div class="form-group">
		<button class="btn btn-primary">SignUp</button>
	</div>
	<center>
		<p>Already have an account?</p>
		<a href="{% url "user_login" %}" class="btn btn-info">Login</a>
	</center>
	</form>

</div>

</body>
</html>

<script type="text/javascript">
	$(".toggle-password").click(function() {
  $(this).toggleClass("fa-eye fa-eye-slash");
  var input = $($(this).attr("toggle"));
  if (input.attr("type") == "password") {
    input.attr("type", "text");
  } else {
    input.attr("type", "password");
  }
});

$(".toggle-confirm_password").click(function() {

$(this).toggleClass("fa-eye fa-eye-slash");
var input = $($(this).attr("toggle"));
if (input.attr("type") == "password") {
	input.attr("type", "text");
} else {
	input.attr("type", "password");
}
});
</script>

mysite/templates/index2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<title>Fitler</title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static "css/style_grid.css"%}">


<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="#services" class="w3-bar-item w3-button w3-padding-large w3-hide-small">SERVICES FOR YOU</a>
    <a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hide-small">CONTACT</a>
    {% if user.is_authenticated%}
      <a href="{% url "user_logout" %}" style = "float:right" class="w3-bar-item w3-button w3-padding-large w3-hide-small" >LOGOUT</a>
      {% if user.get_short_name == "job_seeker" %}
          <a href="{% url "job_seeker:usermodel_list" %}" style = "float:right" class="w3-bar-item w3-button w3-padding-large w3-hide-small">USER DASHBOARD</a>
      {%else%}
          <a href="{% url "company:company_dashboard" %}" style = "float:right" class="w3-bar-item w3-button w3-padding-large w3-hide-small">COMPANY DASHBOARD</a>
      {% endif %}
    {% else %}
      <a href="#login_signup" style = "float:right" class="w3-bar-item w3-button w3-padding-large w3-hide-small">LOGIN</a>
    {% endif %}
  </div>
</div>

<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->
<div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">
  <a href="#services" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">SERVICES FOR YOU</a>
  <a href="#contact" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACT</a>
  <a href="#login_signup" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">LOGIN</a>
</div>


<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">

  <!-- Carousals -->

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <!-- <img src="{% static "images/1.jpg" %}"   style="width:100%;height:600px;"> -->
        <img src="{% static "images/1.jpg" %}"  style="width:100%;height:600px;">
      </div>

      <div class="item">
        <img src="{% static "images/2.jpg" %}"  style="width:100%;height:600px;">
      </div>

      <div class="item">
        <img src="{% static "images/3.jpg" %}" style="width:100%;height:600px;">
      </div>

    <div class="item">
        <img src="{% static "images/4.jpg" %}" style="width:100%;height:600px;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


<!-- The Company and user Section -->
  <div id = "login_signup" id="welcome-page" class="container-fluid">
  {% if not user.is_authenticated %}
  <section class="section-ct one">
    <div class="section one row">
      <div class="col-xs-12 col-sm-6 subsection one" style="background-color: #5cb85c">
        <div class="row">
          <div class="col-xs-offset-1 col-xs-10">
          	<br><br><br>
          	<br><br><br>
            <center><h1 style="color: white;"><b>Company</b></h1></center>
            <br>
            <center><h5 style="margin-bottom: 35px; font-size: 16px; color: white;">Give us time and we help you hire the best candidates.</h5>
            <a href="{% url "company_signup"%}" class="button" style="color: white;"><span> Signup </span></a>
            <a href="{% url "company_login"%}" class="button" style="color: white;"><span> Login </span> </a></center>
            <br><br><br>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 subsection two " style="background-color: #63b1c6">
        <div class="row">
          <div class="col-xs-offset-1 col-xs-10">
          	<br><br><br>
          	<br><br><br>

          <center><h1 style= " color:white "><b>User</b></h1></center>
          	<br>
            <center><h5 style="margin-bottom: 35px; font-size: 16px; color:white">Give us time and we get you the job you deserve.</h5>
            <a href="{% url "user_signup" %}" class="button" style="color: white;"><span> Signup </span></a>
            <a href="{% url "user_login"%}"  class="button" style="color: white;"><span> Login </span> </a></center>
            <br><br><br>
          </div>
        </div>
      </div>
    </div>
    </section>
    {% endif %}
<!-- The SERVICES Section -->
  <div  id="services">
    <center><h2 class="w3-wide">What's in it for you </h2></center>
    <br><br>
    <div class="row">
    	<div class="col-md-4">
    		<img src="{% static "images/10.jpg" %}" class="img-circle" width="300" height="200">
    	</div>

    	<div class="col-md-4">
    		<img src="{% static "images/11.jpg" %}" class="img-circle" width="300" height="200">
    	</div>

    	<div class="col-md-4">
    	   <a href="{% url "editor:typingEditor"%}"><img src="{% static "images/12.jpg" %}" class="img-circle" width="300" height="200"></a>
    	</div>

    </div>
  </div>



 <div class="container-fluid" style="background-color: #63b1c6;">
 	<div class="row"><br><br>
		<div class="col-md-5">

		</div>
		<div class="col-md-2">
			<i class="material-icons" style="font-size: 100px;">public</i>
		</div>

		<div class="col-md-4">
		    <h3 style="color: white;"><b>Global Opportunity</b></h3>
			<p style="color: white;">Get referred to the best opportunities across the globe. We find the relevant profiles and the best of companies.</p>
		</div>
 	</div>

 	<div class="row"><br><br><br>
		<div class="col-md-5">
            <center><h1 style="color: white;"><b>Explore</b></h1></center>
            <center><h1 style="color: white;"><b>Jobs</b></h1></center>
		</div>
		<div class="col-md-2">
			<i class="material-icons" style="font-size: 100px;">chat</i>
		</div>
		<div class="col-md-4">
			<h3 style="color: white;"><b>Coding Interview Experience</b></h3>
			<p style="color: white;">Get recent interview experiences before your interview along with free mentorship for interview preparations</p>
		</div>
 	</div>

 	<div class="row"><br><br><br>
		<div class="col-md-5">

		</div>
		<div class="col-md-2">
			<i class="material-icons" style="font-size: 100px;">money_off</i>
		</div>
		<div class="col-md-4">
			<h3 style="color: white;"><b>Remuneration</b></h3>
			<p style="color: white;">It's absolutely free.</p>
		</div>
 	</div><br><br>
 </div>




  <!-- The Contact Section -->
  <div id="contact">
  <div class="w3-container w3-content w3-padding-64" style="max-width:800px">
    <h2 class="w3-wide w3-center">CONTACT</h2>
    <p class="w3-opacity w3-center"><i>Fan? Drop a note!</i></p>
    <div class="w3-row w3-padding-32">
      <div class="w3-col m6 w3-large w3-margin-bottom">
        <i class="fa fa-map-marker" style="width:30px"></i> Jalandhar, India<br>
        <i class="fa fa-phone" style="width:30px"></i> Phone: +91-9768564567<br>
        <i class="fa fa-envelope" style="width:30px"> </i> Email: rks@gmail.com<br>
      </div>
      <div class="w3-col m6">
        <form action="/action_page.php" target="_blank">
          <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
            <div class="w3-half">
              <input class="w3-input w3-white w3-border" type="text" placeholder="Name" required name="Name">
            </div>
            <div class="w3-half">
              <input class="w3-input w3-white w3-border" type="text" placeholder="Email" required name="Email">
            </div>
          </div>
          <input class="w3-input w3-white w3-border" type="text" placeholder="Message" required name="Message">
          <button class="w3-button w3-black w3-section w3-right" type="submit">SEND</button>
        </form>
      </div>
    </div>
  </div>
  </div>

<!-- End Page Content -->

</div>
<!-- Add Google Maps -->
<!-- <div id="googleMap" style="height:400px;" class="w3-grayscale-max"> -->
  <iframe id = "googleM" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3410.812713692578!2d75.701480314624!3d31.253607567394113!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x391a5a594d22b88d%3A0x4cc934c58d0992ec!2sLovely+Professional+University!5e0!3m2!1sen!2sin!4v1538203930445" width=100% height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
<!-- </div> -->


<!-- Footer -->
<div id="footer">
    <div style="background-color:#373e3f;">
  	<br> <br>

  	<center><button class="btn btn-primary " style="background-color: #373e3f; border-radius: 4px; border-color: white;">Like Us</button> &nbsp; &nbsp; &nbsp; &nbsp;
  	<button class="btn btn-primary " style="background-color: #373e3f; border-radius: 4px; border-color: white;">Follow Us</button>&nbsp; &nbsp; &nbsp; &nbsp;
  	<button class="btn btn-primary " style="background-color: #373e3f; border-radius: 4px; border-color: white;">Contact Us</button></center>
  	<br> <br>




  	<center><ul class="list-inline">
            <li><a href="https://blog.rks.com" target="_blank" style="color: white; font-size: 20px;">Blog </a>&nbsp; &nbsp;<span style="color: white; font-size: 20px;">|</span>&nbsp; &nbsp;</li>

            <li><a href="https://blog.rks.com" target="_blank" style="color: white; font-size: 20px;">About Us </a>&nbsp; &nbsp;<span style="color: white; font-size: 20px;">|</span>&nbsp; &nbsp;</li>

            <li><a href="https://blog.rks.com" target="_blank" style="color: white; font-size: 20px;">FAQ </a>&nbsp; &nbsp;<span style="color: white; font-size: 20px;">|</span>&nbsp; &nbsp;</li>

            <li><a href="https://blog.rks.com" target="_blank" style="color: white; font-size: 20px;">Contact Us </a>&nbsp; &nbsp;<span style="color: white; font-size: 20px;">|</span>&nbsp; &nbsp;</li>

            <li><a href="https://blog.rks.com" target="_blank" style="color: white; font-size: 20px;">Terms </a>&nbsp; &nbsp;<span style="color: white; font-size: 20px;">|</span>&nbsp; &nbsp;</li>

            <li><a href="https://blog.rks.com" target="_blank" style="color: white; font-size: 20px;">Privacy Policy</a></li>

          </ul></center>
  	<br> <br>

  	<div>
  	<center>
  	 <img src="{% static "images/Facebook-Icon.png" %}" width=30 height=30>&nbsp; &nbsp; &nbsp;
  	<img src="{% static "images/twitter-icon-circle-blue-logo-preview-400x400.png"%}" width=30 height=30>&nbsp; &nbsp; &nbsp;
  	<img src="{% static "images/googleplus_512_custom_gloss_red.png"%}" width=30 height=30>&nbsp; &nbsp; &nbsp;
  	<img src="{% static "images/YouTube-icon-full_color.png"%}" width=30 height=30>&nbsp; &nbsp; &nbsp;
  	<img src="{% static "images/Uiconstock-Socialmedia-Instagram.ico"%}" width=30 height=30>&nbsp; &nbsp; &nbsp;
  	<img src="{% static "images/Metro_LinkedIn.png"%}" width=30 height=30>
  	</center>
  	</div>
  	<br> <br>

  </div>


</div>



</body>
</html>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap"></script>





<script>

// $(function(){
//   $('#footer').load('footer1.html');
// });

// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}

// When the user clicks anywhere outside of the modal, close it
var modal = document.getElementById('ticketModal');
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>
<script>
function myMap()
{
    var mapProp=
    {
        center:new google.maps.LatLng(20.5937, 78.9629),
        zoom:5,
    };
    var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
}
</script>