mysite/company/urls.py
from django.conf.urls import url
from company import views

app_name = "company"

urlpatterns = [

    url(r'^$', views.CompanyProfileListView.as_view(), name = "company_dashboard"),
    url(r'^jobs_dashboard/$', views.CompanyJobsDashboard, name='company_jobs_dashboard'),
    url(r'^companyprofile/$', views.CompanyProfileView.as_view(), name = "company_profile_form"),
    url(r'^company_update/(?P<pk>\d+)/$', views.CompanyProfileUpdateView.as_view(), name = 'company_update'),
    url(r'^(?P<pk>\d+)/$', views.CompanyProfileDetailView.as_view(), name = 'company_detail'),
    url(r'^job_dash/$',  views.CompanyJobsDashboard, name = 'company_dash'),

    url(r'^job_create/$', views.JobCreateView.as_view(), name = 'job_create'),
    url(r'^job_update/(?P<pk>\d+)/$', views.JobUpdateView.as_view(), name = 'job_update'),
    url(r'^job_detail/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name = 'job_detail'),
    url(r'^job_delete/(?P<pk>\d+)/$', views.JobDeleteView.as_view(), name = 'job_delete'),
    url(r'^user_object_detail/(?P<candidate_id>\d+)/$', views.ShowCandidateDetail, name = 'user_detail'),
    url(r'^selected/(?P<job_id>\d+)/$', views.Selected, name = "selected"),
    url(r'^rejected/(?P<job_id>\d+)/$', views.Rejected, name = "rejected"),
    url(r'^applicants/$', views.AllApplicantsView, name = "all_applicants"),
    url(r'^candidates/$', views.AllCandidatesView, name = "all_candidates"),
    url(r'^candidate_detail/(?P<key_id>\d+)/$', views.CandidateDisplay, name = "candidate_detail"),
    url(r'^download_resume/(?P<user_id>\d+)/$', views.GetResume, name = "get_resume"),
    url(r'^analysis_page/$', views.AnalysisPage.as_view(), name = "analysis_page")
]

mysite/editor/urls.py
from django.conf.urls import url
from editor import views

app_name = 'editor'

urlpatterns = [
    url(r'^$', views.typingEditor , name = 'typingEditor'),
]

mysite/job_seeker/urls.py
from django.conf.urls import url
from job_seeker import views

app_name = "job_seeker"

urlpatterns = [
    # url(r'^$', views.UserDashBoard.as_view(), name = "user_dashboard"),
    url(r'^$', views.UserModelList.as_view(), name = "usermodel_list"),
    url(r'^(?P<pk>\d+)/$', views.UserProfileDetailView.as_view(), name = "detail"),
    url(r'^personal/$', views.UserProfileCreateView.as_view(), name = "user_profile_form"),
    url(r'^update/(?P<pk>\d+)/$', views.UserProfileUpdateView.as_view(), name = "update_profile_form"),

    url(r'^pro/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name = "project_detail"),
    url(r'^pro_update/(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name = "project_update"),
    url(r'^project/$', views.ProjectCreateView.as_view(), name = "create_project"),
    url(r'^delete/(?P<pk>\d+)/$', views.ProjectDeleteView.as_view(), name = "project_delete"),

    url(r'^skill/$', views.SkillCreateView.as_view(), name = "create_skill"),
    url(r'^skill_update/(?P<pk>\d+)/$', views.SkillUpdateView.as_view(), name = "skill_update"),
    url(r'^skill/(?P<pk>\d+)/$', views.SkillDetailView.as_view(), name = "skill_detail"),
    url(r'^skill_delete/(?P<pk>\d+)/$', views.SkillDeleteView.as_view(), name = "skill_delete"),

    url(r'^award/$', views.AwardCreateView.as_view(), name = "create_award"),
    url(r'^award_update/(?P<pk>\d+)/$', views.AwardUpdateView.as_view(), name = "award_update"),
    url(r'^award/(?P<pk>\d+)/$', views.AwardDetailView.as_view(), name = "award_detail"),
    url(r'^award_delete/(?P<pk>\d+)/$', views.AwardDeleteView.as_view(), name = "award_delete"),

    url(r'^certification/$', views.CertificationCreateView.as_view(), name = "create_certification"),
    url(r'^certification_update/(?P<pk>\d+)/$', views.CertificationUpdateView.as_view(), name = "certification_update"),
    url(r'^certification/(?P<pk>\d+)/$', views.CertificationDetailView.as_view(), name = "certification_detail"),
    url(r'^certification_delete/(?P<pk>\d+)/$', views.CertificationDeleteView.as_view(), name = "certification_delete"),

    url(r'^review1/$', views.Res1.as_view(), name = 'res1'),
    url(r'^review2/$', views.Res2.as_view(), name = 'res2'),
    url(r'^review3/$', views.Res3.as_view(), name = 'res3'),
    url(r'^review4/$', views.Res4.as_view(), name = 'res4'),
    url(r'^review5/$', views.Res5.as_view(), name = 'res5'),

    url(r'^dash/$', views.JobDisplay.as_view(), name = 'job_display'),
    url(r'job_detail/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name = 'job_detail'),
    url(r'apply/(?P<job_id>\d+)', views.JobApply, name = "job_apply"),
    url(r'^cancel_application/(?P<pk>\d+)/$', views.JobsDeleteView.as_view(), name = 'cancel_job'),
    url(r'^all_jobs/$', views.AllJobs.as_view(), name = "all_jobs"),
    url(r'^resume_page/$', views.ResumePage.as_view(), name = "resume_page"),
    url(r'^user_analysis_page/$', views.UserAnalysisPage.as_view(), name = "user_analysis")

]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from registration import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home'),
    url(r'^userlogin/$', views.UserLogin.as_view(), name = "user_login"),
    url(r'^companylogin/$', views.CompanyLogin.as_view(), name = "company_login"),
    url(r'^userlogout/$', views.user_logout, name = "user_logout"),
    url(r'^usersignup/$', views.UserSignUp, name = "user_signup"),
    url(r'^companysignup/$', views.CompanySignUp, name = "company_signup"),
    url(r'^job_seeker/',include('job_seeker.urls', namespace = "job_seeker") ),
    url(r'^company/', include('company.urls'), name = "company"),
    url(r'^editor/', include('editor.urls'), name = "editor")
]

mysite/company/models.py
import datetime
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
# Create your models here.

class CompanyModel(models.Model):
    user = models.ForeignKey(User, related_name='company_det',on_delete = models.CASCADE)

    company_name = models.CharField(max_length = 100, null = False, blank = False)
    company_field = models.CharField(max_length = 100, null = False, blank = False)
    comapany_country = models.CharField(max_length = 100, null = False, blank = False)
    company_email = models.EmailField(null = False, blank = True)
    company_contact = models.PositiveIntegerField(null = False, blank = False)
    company_website = models.URLField(null = True, blank = True)
    company_description = models.CharField(max_length = 400, blank = False, null = False)

    def __str__(self):
        return self.company_name

    def get_absolute_url(self):
        return reverse(
            "company:company_detail",
            kwargs={
                "pk": self.pk
            }
        )

class Job(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    profile_choices = (
        ('Business Development (Sales)', 'Business Development (Sales)'),
        ('Web Development', 'Web Development'),('Graphic Design','Graphic Design'),
        ('Content Writing','Content Writing'),('Operations','Operations'),('Mobile App Development','Mobile App Development'),
        ('Social Media Marketing','Social Media Marketing'),
        ('Marketing','Marketing'),('Digital Marketing','Digital Marketing'),
        ('Human Resources (HR)', 'Human Resources (HR)'),
        ('Law/ Legal', 'Law/ Legal'),('Campus Ambassador', 'Campus Ambassador')
        )
    type_choices = (
        ('Regular', 'Regular (In-office/On-field)'),
        ('Work From Home', 'Work From Home')
    )

    company_name = models.CharField(max_length = 100, null = True)
    company_website = models.URLField(null = True, blank = True)
    company_email = models.EmailField(null = True, blank = True)
    job_profile = models.CharField(max_length = 100, choices = profile_choices, null = False)
    job_type = models.CharField(max_length = 100, choices = type_choices, null = False)
    job_location = models.CharField(max_length = 100, null = False, blank = False)
    job_vacancy = models.PositiveIntegerField(null = True, blank = True)
    posted_date = models.DateField(default=datetime.date.today)
    date_from = models.DateField(null = False)
    date_till = models.DateField(null = False)
    job_description = models.CharField(max_length = 400, blank = False, null = False)
    salary = models.PositiveIntegerField(null = False, blank = False)
    perks = models.CharField(max_length = 300, blank = True, null = True)

    def __str__(self):
        return self.job_profile+ " : Rs" +str(self.salary)

    def get_absolute_url(self):
        return reverse(
            "company:job_detail",
            kwargs={
                "pk": self.pk
            }
        )

mysite/job_seeker/forms.py
from django import forms
from job_seeker.models import UserModel, Project, Skill, Award, Certification

class UserModelForm(forms.ModelForm):

    full_name = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Full Name'}
    ), required = True, max_length = 100)

    user_email = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'User Email'}
    ), required = True, max_length = 100)

    # gender = forms.ChoiceField(widget = forms.Select(
    #     choices = (('Male','Male'), ('Female','Female'))
    # ), required = True)

    date_of_birth = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Date of Birth', 'type':'date'}
    ), required = True)

    mobile_number = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Mobile Number', 'type':'number'}
    ), required = True, max_length = 100)

    # options radio buttons

    address_line1 = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Address Line 1'}
    ), required = True, max_length = 100)

    address_line2 = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Address Line 2'}
    ), max_length = 100)

    city = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'City'}
    ), required = True, max_length = 100)

    state = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'State'}
    ), required = True, max_length = 100)

    zip = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Pincode', 'type':'number'}
    ), required = True, max_length = 100)

    tenth_institution = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Tenth School'}
    ), required = True, max_length = 100)

    tenth_board = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Tenth Board'}
    ), required = True, max_length = 100)

    tenth_result = forms.DecimalField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Tenth Result'}
    ), required = True, max_digits = 5)

    tenth_date = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Tenth completion', 'type':'date'}
    ), required = True)

    twelfth_institution = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Twelfth School'}
    ), required = True, max_length = 100)

    twelfth_board = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Twelfth Board'}
    ), required = True, max_length = 100)

    twelfth_result = forms.DecimalField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Twelfth Result'}
    ), required = True, max_digits = 5)

    twelfth_date = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Twelfth completion date', 'type':'date'}
    ), required = True)

    diploma_institution = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Diploma Institute'}
    ),required = False, max_length = 100)

    diploma_board = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Board'}
    ),required = False, max_length = 100)

    diploma_result = forms.DecimalField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Result'}
    ),required = False, max_digits = 5)

    diploma_date = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Passing Date','type':'date'}
    ),required = False)

    bachelor_institution = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Institute Name'}
    ), required = True, max_length = 100)

    bachelor_board = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Board Name'}
    ), required = True, max_length = 100)

    bachelor_program = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Program Name'}
    ), required = False, max_length = 100)

    bachelor_stream = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Stream'}
    ),required = False, max_length = 100)

    bachelor_result = forms.DecimalField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Bachelor Result'}
    ), required = True, max_digits = 5)

    bachelor_date = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Passing Date', 'type':'date'}
    ), required = True)

    resume_headline = forms.CharField(widget = forms.Textarea(
        attrs = {'class':'form-control', 'placeholder':'Your Resume Headline', 'rows':'3'}
    ), required = True, max_length = 200)

    extra_curriculam = forms.CharField(widget = forms.Textarea(
        attrs = {'class':'form-control', 'placeholder':'Type items seperated by comma eg: Debate, Elocution ', 'rows':'7'}
    ), required = True, max_length = 500)

    hobies = forms.CharField(widget = forms.Textarea(
        attrs = {'class':'form-control', 'placeholder':'Type items seperated by comma eg: Cooking,Reading ', 'rows':'7'}
    ), required = True, max_length = 500)


    class Meta:
        model = UserModel
        exclude = ('user',)

class ProjectForm(forms.ModelForm):
    project_name = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Project Name'}
    ), required = True, max_length = 100)

    project_link = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Project Link'}
    ), required = True, max_length = 100)

    project_description = forms.CharField(widget = forms.Textarea(
        attrs = {'class':'form-control', 'placeholder':'Project Description', 'rows':'7'}
    ), required = True, max_length = 100)

    start_date =  forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Start Date', 'type':'date'}
    ), required = True, max_length = 100)

    end_date = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'End Date', 'type':'date'}
    ), required = True, max_length = 100)


    class Meta:
        model = Project
        exclude = ('user',)

class SkillForm(forms.ModelForm):

    skill_name = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Skill Name'}
    ), required = True, max_length = 100)

    class Meta:
        model = Skill
        exclude = ('user',)

class AwardForm(forms.ModelForm):
    award_name = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Award Name'}
    ), required = True, max_length = 100)

    award_organization = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Organization Name'}
    ), required = True, max_length = 100)

    award_description = forms.CharField(widget = forms.Textarea(
        attrs = {'class':'form-control', 'placeholder':'Award Description', 'rows':'7'}
    ), required = True, max_length = 100)

    class Meta:
        model = Award
        exclude = ('user',)


class CertificationForm(forms.ModelForm):
    certification_name = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Certification Name'}
    ), required = True, max_length = 100)

    certification_organization = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Organization Name'}
    ), required = True, max_length = 100)

    certificate_link = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Certificate Link'}
    ), required = True, max_length = 100)

    valid_from = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Passing Date', 'type':'date'}
    ), required = True)

    valid_till = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Passing Date', 'type':'date'}
    ), required = True)

    class Meta:
        model = Certification
        widgets = {
            'valid_from': forms.SelectDateWidget(),
            'valid_till' : forms.SelectDateWidget(),
        }
        exclude = ('user',)

mysite/job_seeker/templates/usermodel_list.html
<!DOCTYPE html>
{% load staticfiles%}
<html >
<head>

  <!-- Site made with Mobirise Website Builder v4.8.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.8.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/jf-96x96.png' %}" type="image/x-icon">
  <meta name="description" content="">
  <title>Home</title>
  <link rel="stylesheet" href="{%static 'assets/web/assets/mobirise-icons/mobirise-icons.css'%}">
  <link rel="stylesheet" href="{%static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{%static 'assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{%static 'assets/as-pie-progress/css/progress.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/theme/css/style.css' %}">
  <link rel="stylesheet" href="{%static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">


  <!-- Login CSS -->
  <link rel="stylesheet" href="{%static 'assets/mobirise/css/style_grid.css' %}">
	<link rel="stylesheet" href="{%static 'assets/mobirise/css/panel.css' %}">


</head>
<body>
  <style media="screen">
    body{
      margin-top:100px;
    }
  </style>
  <section class="menu cid-rakr8DWKxw" once="menu" id="menu1-3">



    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'home' %}">
                         <img src="{% static 'assets/images/jf-96x96.png' %}" alt="Mobirise" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="{% url 'home'%}">Job Free</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
              {% if user.is_authenticated%}
                <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'user_logout' %}"><span class="mbri-logout mbr-iconfont mbr-iconfont-btn"></span>Logout</a></li>
                {% if user.get_short_name == "job_seeker" %}
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'job_seeker:usermodel_list' %}"><span class="mbri-edit mbr-iconfont mbr-iconfont-btn"></span>User Details</a></li>
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'job_seeker:job_display'%}"><span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>Dashboard</a></li>
                {% else %}
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'company:company_dashboard' %}"><span class="mbri-letter mbr-iconfont mbr-iconfont-btn"></span>Post</a></li>
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'company:company_jobs_dashboard'%}"><span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>Dashboard</a>
                {% endif %}
              {% else %}
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="#login-signup"><span class="mbri-login mbr-iconfont mbr-iconfont-btn"></span>Login/Signup</a></li>
              {% endif %}
            </ul>

        </div>
    </nav>
</section>


<div class="container">
  <h1>Personal Details</h1>
  <div class="jumbotron">
    {% if user_models %}
      {% for seeker in user_models %}
      <a href="{{seeker.id}}" class = "btn btn-primary btn-sm" style = "width:300px;">{{ seeker.full_name }}</a>
      {% endfor %}
    {% else %}
      <a href="{% url 'job_seeker:user_profile_form' %}" class="btn btn-primary btn-sm">Create</a>
    {% endif %}
  </div>
</div>

<!-- Division related to the Projects fo the User -->
<div class="container">
  <h1>Projects</h1>
  <div class="jumbotron">
    <ol>
      {% for project in project_list %}
        <li><a href="pro/{{ project.id }}" class="btn btn-warning btn-sm" style= "width:300px;">{{ project.project_name }}</a></li>
        <br>
      {% endfor %}
    </ol>
    <a href="{% url 'job_seeker:create_project' %}" class="btn btn-primary btn-sm">Add Project</a>
  </div>
</div>


<!-- Division related to the Skills of the User -->
<div class="container">
  <h1>Skills</h1>
  <div class="jumbotron">
    <ol>
      {% for skill in skill_list %}
        <li><a href="skill/{{ skill.id }}" class="btn btn-warning btn-sm" style= "width:150px;">{{ skill.skill_name }}</a></li>
        <br>
      {% endfor %}
    </ol>
    <a href="{% url 'job_seeker:create_skill' %}" class="btn btn-primary btn-sm">Add Skill</a>
  </div>
</div>


<!-- Division related to the Awards of the User -->
<div class="container">
  <h1>Awards</h1>
  <div class="jumbotron">
    <ol>
      {% for award in award_list %}
        <li><a href="award/{{ award.id }}" class="btn btn-warning btn-sm" style= "width:220px;">{{ award.award_name }}</a></li>
        <br>
      {% endfor %}
    </ol>
    <a href="{% url 'job_seeker:create_award' %}" class="btn btn-primary btn-sm">Add Award</a>
  </div>
</div>


<!-- Division related to the Certifications of the User -->
<div class="container">
  <h1>Certifications</h1>
  <div class="jumbotron">
    <ol>
      {% for certification in certification_list %}
        <li><a href="certification/{{ certification.id }}" class="btn btn-warning btn-sm" style= "width:220px;">{{ certification.certification_name }}</a></li>
        <br>
      {% endfor %}
    </ol>
    <a href="{% url 'job_seeker:create_certification' %}" class="btn btn-primary btn-sm">Add Certification</a>
  </div>
  <a href="{% url 'job_seeker:res1'%}" class="btn btn-success">Review</a>
</div>


<section class="cid-rakvqG7Egd" id="social-buttons3-8">





    <div class="container">
        <div class="media-container-row">
            <div class="col-md-8 align-center">
                <h2 class="pb-3 mbr-section-title mbr-fonts-style display-2">
                    SHARE THIS PAGE!
                </h2>
                <div>
                    <div class="mbr-social-likes">
                        <span class="btn btn-social socicon-bg-facebook facebook mx-2" title="Share link on Facebook">
                            <i class="socicon socicon-facebook"></i>
                        </span>
                        <span class="btn btn-social twitter socicon-bg-twitter mx-2" title="Share link on Twitter">
                            <i class="socicon socicon-twitter"></i>
                        </span>
                        <span class="btn btn-social plusone socicon-bg-googleplus mx-2" title="Share link on Google+">
                            <i class="socicon socicon-googleplus"></i>
                        </span>


                        <span class="btn btn-social pinterest socicon-bg-pinterest mx-2" title="Share link on Pinterest">
                            <i class="socicon socicon-pinterest"></i>
                        </span>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section once="" class="cid-rakvx6YUQs" id="footer6-a">





    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">
                    © Copyright 2018 Job Free - All Rights Reserved
                </p>
            </div>
        </div>
    </div>
</section>


  <script src="{%static 'assets/web/assets/jquery/jquery.min.js'%}"></script>
  <script src="{%static 'assets/popper/popper.min.js'%}"></script>
  <script src="{%static 'assets/tether/tether.min.js'%}"></script>
  <script src="{%static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
  <script src="{%static 'assets/smoothscroll/smooth-scroll.js'%}"></script>
  <script src="{%static 'assets/dropdown/js/script.min.js'%}"></script>
  <script src="{%static 'assets/touchswipe/jquery.touch-swipe.min.js'%}"></script>
  <script src="{%static 'assets/ytplayer/jquery.mb.ytplayer.min.js'%}"></script>
  <script src="{%static 'assets/vimeoplayer/jquery.mb.vimeo_player.js'%}"></script>
  <script src="{%static 'assets/bootstrapcarouselswipe/bootstrap-carousel-swipe.js'%}"></script>
  <script src="{%static 'assets/mbr-flip-card/mbr-flip-card.js'%}"></script>
  <script src="{%static 'assets/parallax/jarallax.min.js'%}"></script>
  <script src="{%static 'assets/as-pie-progress/jquery-as-pie-progress.min.js'%}"></script>
  <script src="{%static 'assets/sociallikes/social-likes.js'%}"></script>
  <script src="{%static 'assets/theme/js/script.js'%}"></script>
  <script src="{%static 'assets/slidervideo/script.js'%}"></script>
  <script src="{%static 'assets/formoid/formoid.min.js'%}"></script>


</body>
</html>