mysite/company/urls.py
from django.conf.urls import url
from company import views

app_name = "company"

urlpatterns = [

    url(r'^$', views.CompanyProfileListView.as_view(), name = "company_dashboard"),
    url(r'^jobs_dashboard/$', views.CompanyJobsDashboard, name='company_jobs_dashboard'),
    url(r'^companyprofile/$', views.CompanyProfileView.as_view(), name = "company_profile_form"),
    url(r'^company_update/(?P<pk>\d+)/$', views.CompanyProfileUpdateView.as_view(), name = 'company_update'),
    url(r'^(?P<pk>\d+)/$', views.CompanyProfileDetailView.as_view(), name = 'company_detail'),
    url(r'^job_dash/$',  views.CompanyJobsDashboard, name = 'company_dash'),

    url(r'^job_create/$', views.JobCreateView.as_view(), name = 'job_create'),
    url(r'^job_update/(?P<pk>\d+)/$', views.JobUpdateView.as_view(), name = 'job_update'),
    url(r'^job_detail/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name = 'job_detail'),
    url(r'^job_delete/(?P<pk>\d+)/$', views.JobDeleteView.as_view(), name = 'job_delete'),
    url(r'^user_object_detail/(?P<candidate_id>\d+)/$', views.ShowCandidateDetail, name = 'user_detail'),
    url(r'^selected/(?P<job_id>\d+)/$', views.Selected, name = "selected"),
    url(r'^rejected/(?P<job_id>\d+)/$', views.Rejected, name = "rejected"),
    url(r'^applicants/$', views.AllApplicantsView, name = "all_applicants"),
    url(r'^candidates/$', views.AllCandidatesView, name = "all_candidates"),
    url(r'^candidate_detail/(?P<key_id>\d+)/$', views.CandidateDisplay, name = "candidate_detail"),
    url(r'^download_resume/(?P<user_id>\d+)/$', views.GetResume, name = "get_resume"),
    url(r'^analysis_page/$', views.AnalysisPage.as_view(), name = "analysis_page")
]

mysite/editor/urls.py
from django.conf.urls import url
from editor import views

app_name = 'editor'

urlpatterns = [
    url(r'^$', views.typingEditor , name = 'typingEditor'),
]

mysite/job_seeker/urls.py
from django.conf.urls import url
from job_seeker import views

app_name = "job_seeker"

urlpatterns = [
    # url(r'^$', views.UserDashBoard.as_view(), name = "user_dashboard"),
    url(r'^$', views.UserModelList.as_view(), name = "usermodel_list"),
    url(r'^(?P<pk>\d+)/$', views.UserProfileDetailView.as_view(), name = "detail"),
    url(r'^personal/$', views.UserProfileCreateView.as_view(), name = "user_profile_form"),
    url(r'^update/(?P<pk>\d+)/$', views.UserProfileUpdateView.as_view(), name = "update_profile_form"),

    url(r'^pro/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name = "project_detail"),
    url(r'^pro_update/(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name = "project_update"),
    url(r'^project/$', views.ProjectCreateView.as_view(), name = "create_project"),
    url(r'^delete/(?P<pk>\d+)/$', views.ProjectDeleteView.as_view(), name = "project_delete"),

    url(r'^skill/$', views.SkillCreateView.as_view(), name = "create_skill"),
    url(r'^skill_update/(?P<pk>\d+)/$', views.SkillUpdateView.as_view(), name = "skill_update"),
    url(r'^skill/(?P<pk>\d+)/$', views.SkillDetailView.as_view(), name = "skill_detail"),
    url(r'^skill_delete/(?P<pk>\d+)/$', views.SkillDeleteView.as_view(), name = "skill_delete"),

    url(r'^award/$', views.AwardCreateView.as_view(), name = "create_award"),
    url(r'^award_update/(?P<pk>\d+)/$', views.AwardUpdateView.as_view(), name = "award_update"),
    url(r'^award/(?P<pk>\d+)/$', views.AwardDetailView.as_view(), name = "award_detail"),
    url(r'^award_delete/(?P<pk>\d+)/$', views.AwardDeleteView.as_view(), name = "award_delete"),

    url(r'^certification/$', views.CertificationCreateView.as_view(), name = "create_certification"),
    url(r'^certification_update/(?P<pk>\d+)/$', views.CertificationUpdateView.as_view(), name = "certification_update"),
    url(r'^certification/(?P<pk>\d+)/$', views.CertificationDetailView.as_view(), name = "certification_detail"),
    url(r'^certification_delete/(?P<pk>\d+)/$', views.CertificationDeleteView.as_view(), name = "certification_delete"),

    url(r'^review1/$', views.Res1.as_view(), name = 'res1'),
    url(r'^review2/$', views.Res2.as_view(), name = 'res2'),
    url(r'^review3/$', views.Res3.as_view(), name = 'res3'),
    url(r'^review4/$', views.Res4.as_view(), name = 'res4'),
    url(r'^review5/$', views.Res5.as_view(), name = 'res5'),

    url(r'^dash/$', views.JobDisplay.as_view(), name = 'job_display'),
    url(r'job_detail/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name = 'job_detail'),
    url(r'apply/(?P<job_id>\d+)', views.JobApply, name = "job_apply"),
    url(r'^cancel_application/(?P<pk>\d+)/$', views.JobsDeleteView.as_view(), name = 'cancel_job'),
    url(r'^all_jobs/$', views.AllJobs.as_view(), name = "all_jobs"),
    url(r'^resume_page/$', views.ResumePage.as_view(), name = "resume_page"),
    url(r'^user_analysis_page/$', views.UserAnalysisPage.as_view(), name = "user_analysis")

]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from registration import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home'),
    url(r'^userlogin/$', views.UserLogin.as_view(), name = "user_login"),
    url(r'^companylogin/$', views.CompanyLogin.as_view(), name = "company_login"),
    url(r'^userlogout/$', views.user_logout, name = "user_logout"),
    url(r'^usersignup/$', views.UserSignUp, name = "user_signup"),
    url(r'^companysignup/$', views.CompanySignUp, name = "company_signup"),
    url(r'^job_seeker/',include('job_seeker.urls', namespace = "job_seeker") ),
    url(r'^company/', include('company.urls'), name = "company"),
    url(r'^editor/', include('editor.urls'), name = "editor")
]

mysite/company/models.py
import datetime
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
# Create your models here.

class CompanyModel(models.Model):
    user = models.ForeignKey(User, related_name='company_det',on_delete = models.CASCADE)

    company_name = models.CharField(max_length = 100, null = False, blank = False)
    company_field = models.CharField(max_length = 100, null = False, blank = False)
    comapany_country = models.CharField(max_length = 100, null = False, blank = False)
    company_email = models.EmailField(null = False, blank = True)
    company_contact = models.PositiveIntegerField(null = False, blank = False)
    company_website = models.URLField(null = True, blank = True)
    company_description = models.CharField(max_length = 400, blank = False, null = False)

    def __str__(self):
        return self.company_name

    def get_absolute_url(self):
        return reverse(
            "company:company_detail",
            kwargs={
                "pk": self.pk
            }
        )

class Job(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    profile_choices = (
        ('Business Development (Sales)', 'Business Development (Sales)'),
        ('Web Development', 'Web Development'),('Graphic Design','Graphic Design'),
        ('Content Writing','Content Writing'),('Operations','Operations'),('Mobile App Development','Mobile App Development'),
        ('Social Media Marketing','Social Media Marketing'),
        ('Marketing','Marketing'),('Digital Marketing','Digital Marketing'),
        ('Human Resources (HR)', 'Human Resources (HR)'),
        ('Law/ Legal', 'Law/ Legal'),('Campus Ambassador', 'Campus Ambassador')
        )
    type_choices = (
        ('Regular', 'Regular (In-office/On-field)'),
        ('Work From Home', 'Work From Home')
    )

    company_name = models.CharField(max_length = 100, null = True)
    company_website = models.URLField(null = True, blank = True)
    company_email = models.EmailField(null = True, blank = True)
    job_profile = models.CharField(max_length = 100, choices = profile_choices, null = False)
    job_type = models.CharField(max_length = 100, choices = type_choices, null = False)
    job_location = models.CharField(max_length = 100, null = False, blank = False)
    job_vacancy = models.PositiveIntegerField(null = True, blank = True)
    posted_date = models.DateField(default=datetime.date.today)
    date_from = models.DateField(null = False)
    date_till = models.DateField(null = False)
    job_description = models.CharField(max_length = 400, blank = False, null = False)
    salary = models.PositiveIntegerField(null = False, blank = False)
    perks = models.CharField(max_length = 300, blank = True, null = True)

    def __str__(self):
        return self.job_profile+ " : Rs" +str(self.salary)

    def get_absolute_url(self):
        return reverse(
            "company:job_detail",
            kwargs={
                "pk": self.pk
            }
        )

mysite/company/forms.py
from django import forms
from company.models import CompanyModel, Job


class CompanyProfileForm(forms.ModelForm):

    company_name = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Company Name'}
    ), required = True, max_length = 100)

    company_field = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Company Field'}
    ), required = True, max_length = 100)

    company_email = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Company Email'}
    ), required = True, max_length = 100)

    comapany_country = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Country Name'}
    ), required = True, max_length = 100)

    company_contact = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Company Contact','type':'tel'}
    ), required = True, max_length = 10)

    company_description = forms.CharField(widget = forms.Textarea(
        attrs = {'class':'form-control', 'placeholder':'Company Description', 'rows':'7'}
    ), required = True, max_length = 400)

    class Meta:
        model = CompanyModel
        exclude = ('user',)

class JobForm(forms.ModelForm):

    company_name = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Company Name'}
    ), required = True, max_length = 100)

    company_website = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Company Website'}
    ), required = True, max_length = 100)

    company_email = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Company Email'}
    ), required = True, max_length = 100)

    job_location = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Job Location'}
    ), required = True, max_length = 100)

    job_vacancy = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Vacancy', 'type':'number'}
    ), required = True, max_length = 100)

    date_from = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Start Date', 'type':'date'}
    ), required = True)

    date_till = forms.DateField(widget = forms.DateInput(
        attrs = {'class':'form-control', 'placeholder':'Last Date', 'type':'date'}
    ), required = True)

    job_description = forms.CharField(widget = forms.Textarea(
        attrs = {'class':'form-control', 'placeholder':'Job Description', 'rows':'6'}
    ), required = True, max_length = 400)

    salary = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Salary', 'type':'number'}
    ), required = True, max_length = 30)

    perks = forms.CharField(widget = forms.TextInput(
        attrs = {'class':'form-control', 'placeholder':'Perks seperated by , eg:Casual Dress,Snacks '}
    ), required = True, max_length = 300)

    class Meta:
        model = Job
        widgets = {
            'job_profile':forms.RadioSelect(),
            'job_type':forms.RadioSelect(),
        }
        exclude = ('user','posted_date')

mysite/company/templates/company_jobs_dashboard1.html
<!DOCTYPE html>
{% load staticfiles%}
<html >
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.8.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/jf-96x96.png' %}" type="image/x-icon">
  <meta name="description" content="">
  <title>Company Dashboard</title>
  <link rel="stylesheet" href="{% static 'assets_table/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/datatables/data-tables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets_table/theme/css/style.css' %}">


  <link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>

  <!-- old -->
  <link rel="stylesheet" href="{%static 'assets/web/assets/mobirise-icons/mobirise-icons.css'%}">
  <link rel="stylesheet" href="{%static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{%static 'assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{%static 'assets/as-pie-progress/css/progress.min.css' %}">
  <link rel="stylesheet" href="{%static 'assets/theme/css/style.css' %}">
  <link rel="stylesheet" href="{%static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">



</head>
<body>
  <style media="screen">
    body{
      margin-top:10px;
      margin-bottom:0px;
    }
  </style>
  <section class="menu cid-rakr8DWKxw" once="menu" id="menu1-3">



    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'home' %}">
                         <img src="{% static 'assets/images/jf-96x96.png' %}" alt="Mobirise" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="{% url 'home'%}">Job Free</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
              {% if user.is_authenticated%}
                <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'user_logout' %}"><span class="mbri-logout mbr-iconfont mbr-iconfont-btn"></span>Logout</a></li>
                {% if user.get_short_name == "job_seeker" %}
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'job_seeker:usermodel_list' %}"><span class="mbri-edit mbr-iconfont mbr-iconfont-btn"></span>User Details</a></li>
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'job_seeker:job_display'%}"><span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>Dashboard</a></li>
                {% else %}
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'company:company_dashboard' %}"><span class="mbri-letter mbr-iconfont mbr-iconfont-btn"></span>Post</a></li>
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="{% url 'company:company_jobs_dashboard'%}"><span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>Dashboard</a>
                {% endif %}
              {% else %}
                  <li class="nav-item"><a class="nav-link link text-white display-7" href="#login-signup"><span class="mbri-login mbr-iconfont mbr-iconfont-btn"></span>Login/Signup</a></li>
              {% endif %}
            </ul>

        </div>
    </nav>
</section>


<!-- Body Block -->

<section class="engine"><a href="https://mobirise.info/n">free simple web templates</a></section>

<section class="section-table cid-rawUlmObBm" id="table1-6" style = "background-color:white;">

  <div class="container container-table">

    <style media="screen">
      #outer
        {
            width:100%;

        }
        .inner
        {
            display: inline-block;
        }
    </style>
    <div class="align-right">

    <div id="outer">
        <div class="inner">
          <div class="navbar-buttons mbr-section-btn align-right">
              <a id = "red" class="btn btn-sm btn-success display-4" href="{% url 'company:company_dash' %}">All Posts</a>
          </div>
        </div>
        <div class="inner">
          <div class="navbar-buttons mbr-section-btn align-right">
              <a class="btn btn-sm btn-primary display-4" href="{% url 'company:all_candidates' %}">All Candidates</a>
          </div>
        </div>
    </div>
    </div>

      <h2 class="mbr-section-title mbr-fonts-style align-center pb-3 display-2">
          All Applicants</h2>

      <h3 class="mbr-section-subtitle mbr-fonts-style align-center pb-5 mbr-light display-5">
            List of all the applicants who are eagerly waiting to join your company!</h3>
      <div class="table-wrapper">
        <div class="container">
          <div class="row search">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <div class="dataTables_filter">
                  <label class="searchInfo mbr-fonts-style display-7">Search:</label>
                  <input class="form-control input-sm" disabled="">
                </div>
            </div>
          </div>
        </div>

        <div class="container scroll">
          <table class="table isSearch" cellspacing="0">
            <thead>
              <tr class="table-heads ">




              <th class="head-item mbr-fonts-style display-7">NAME</th><th class="head-item mbr-fonts-style display-7">
                      GENDER</th><th class="head-item mbr-fonts-style display-7">
                      CITY</th><th class="head-item mbr-fonts-style display-7">SKILLS</th><th class="head-item mbr-fonts-style display-7">
                      APPLIED FOR</th><th class="head-item mbr-fonts-style display-7">
                      CONTACT NUMBER</th><th class="head-item mbr-fonts-style display-7">
                      EMAIL ID</th><th class="head-item mbr-fonts-style display-7">
                      VIEW DETAILS</th><th class="head-item mbr-fonts-style display-7">
                      RESUME</th><th class="head-item mbr-fonts-style display-7">
                      SELECT/REJECT</th></tr>
            </thead>

            <tbody>



            {% for applicant in applicants %}
            <tr>

              <td class="body-item mbr-fonts-style display-7">{{ applicant.0.full_name }}</td>
              <td class="body-item mbr-fonts-style display-7">{{ applicant.0.gender }}</td>
              <td class="body-item mbr-fonts-style display-7">{{ applicant.0.city }}</td>
              <td class="body-item mbr-fonts-style display-7">
                {% for skill in applicant.2 %}
                  {{ skill }}
                {% endfor %}
              </td>
              <td class="body-item mbr-fonts-style display-7">
                {{ applicant.1.job.job_profile }}
              </td>
              <td class="body-item mbr-fonts-style display-7">
                {{ applicant.0.mobile_number }}
              </td>

              <td class="body-item mbr-fonts-style display-7">
                {{ applicant.0.user_email }}
              </td>

              <td class="body-item mbr-fonts-style display-7">
                <a href="{% url 'company:user_detail' applicant.1.id %}">View Details</a>
              </td>

              <td class="body-item mbr-fonts-style display-7">
                <a href="{% url 'company:get_resume' applicant.1.user.id %}">Download</a>
              </td>


              <td class="body-item mbr-fonts-style display-7">
                {% if applicant.1.job_status == "Applied" or applicant.1.job_status == "Reviewed" %}

                    <a style = "color:green;" href="{% url 'company:selected' applicant.1.id %}">Select</a>
                    <a style = "color:red;" href="{% url 'company:rejected' applicant.1.id %}">Reject</a>

                {% endif %}

                {% if applicant.1.job_status == "Rejected" %}

                  <span style = "color:red;"><b>Rejected</b></span>

                {% endif %}

                {% if applicant.1.job_status == "Selected" %}

                  <span style = "color:green;"><b>Selected</b></span>

                {% endif %}

             </td>

            </tr>
          {% endfor %}


            </tbody>
          </table>
        </div>
        <div class="container table-info-container">
          <div class="row info">
            <div class="col-md-6">
              <div class="dataTables_info mbr-fonts-style display-7">
                <span class="infoBefore">Showing</span>
                <span class="inactive infoRows"></span>
                <span class="infoAfter">entries</span>
                <span class="infoFilteredBefore">(filtered from</span>
                <span class="inactive infoRows"></span>
                <span class="infoFilteredAfter"> total entries)</span>
              </div>
            </div>
            <div class="col-md-6"></div>
          </div>
        </div>
      </div>
    </div>
</section>

<section class="cid-rawZ26RP8Y" id="social-buttons3-8">


<!-- End Block -->

<section  class="cid-rakvqG7Egd" id="social-buttons3-8">


    <div class="container">
        <div class="media-container-row">
            <div class="col-md-8 align-center">
                <h2 class="pb-3 mbr-section-title mbr-fonts-style display-2">
                    SHARE THIS PAGE!
                </h2>
                <div>
                    <div class="mbr-social-likes">
                        <span class="btn btn-social socicon-bg-facebook facebook mx-2" title="Share link on Facebook">
                            <i class="socicon socicon-facebook"></i>
                        </span>
                        <span class="btn btn-social twitter socicon-bg-twitter mx-2" title="Share link on Twitter">
                            <i class="socicon socicon-twitter"></i>
                        </span>
                        <span class="btn btn-social plusone socicon-bg-googleplus mx-2" title="Share link on Google+">
                            <i class="socicon socicon-googleplus"></i>
                        </span>


                        <span class="btn btn-social pinterest socicon-bg-pinterest mx-2" title="Share link on Pinterest">
                            <i class="socicon socicon-pinterest"></i>
                        </span>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section once="" class="cid-rakvx6YUQs" id="footer6-a">

    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">
                    © Copyright 2018 Job Free - All Rights Reserved
                </p>
            </div>
        </div>
    </div>
</section>

  <script src="{% static 'assets_table/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets_table/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets_table/tether/tether.min.js' %}"></script>
  <script src="{% static 'assets_table/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets_table/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets_table/touchswipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static 'assets_table/datatables/jquery.data-tables.min.js' %}"></script>
  <script src="{% static 'assets_table/datatables/data-tables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'assets_table/sociallikes/social-likes.js' %}"></script>
  <script src="{% static 'assets_table/dropdown/js/script.min.js' %}"></script>
  <script src="{% static 'assets_table/theme/js/script.js' %}"></script>

</body>
</html>